services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - "5672:5672"
        - "15672:15672"
    volumes:
        - rabbitmq-data:/var/lib/rabbitmq/
    env_file:
      - .env
    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit consumer_timeout 36000000"
  server:
    image: ghcr.io/neferin12/aur-builder-server:1
    container_name: 'aur-builder-server'
    build:
        context: .
        dockerfile: Dockerfile
        target: server
    env_file:
      - .env
    environment:
      AB_CONFIG_PATH: /config.yaml
    volumes:
      - ./db:/app/db
      - ./config.yaml:/config.yaml
    depends_on:
      - rabbitmq
    restart: always
  worker:
    image: ghcr.io/neferin12/aur-builder-worker:1
    deploy:
        mode: replicated
        replicas: 2
    build:
        context: .
        dockerfile: Dockerfile
        target: worker
    env_file:
      - .env
    depends_on:
      - rabbitmq
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
  web:
    image: ghcr.io/neferin12/aur-builder-web:1
    build:
      context: .
      dockerfile: Dockerfile
      target: web
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
    volumes:
      - ./db:/app/db
volumes:
    rabbitmq-data: