#! /bin/bash

cd ~/source || exit 1
# Install all dependencies
echo "INFO: installing all missing dependencies..."
makepkg --printsrcinfo > SINFO
while read -r -u 9 key value;
do
    if [ "$key" == "depends" ];
    then
        DEP=$(echo "$value" | cut -d ' ' -f2 | cut -d '>' -f1)
        echo "installing $DEP..."
        yay --noconfirm --removemake -S "$DEP"
    fi
done 9< "SINFO"