#! /bin/bash

cd ~/source || exit 100

if [[ -n "$AB_SUBFOLDER" ]]; then
    cd "$AB_SUBFOLDER" || exit 100
fi

# Install all dependencies
echo "INFO: updating packages..."
yay --noconfirm --removemake -Syu || exit 103

echo "INFO: installing all missing dependencies..."
makepkg --printsrcinfo > SINFO
while read -r -u 9 key value;
do
    if [ "$key" == "depends" ];
    then
        DEP=$(echo "$value" | cut -d ' ' -f2 | cut -d '>' -f1)
        echo "installing $DEP..."
        yay --mflags "--nocheck" --noconfirm --removemake -S "$DEP" || exit 104
    fi
done 9< "SINFO"