//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "package_metadata")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub version: String,
    pub maintainer: String,
    pub last_modified: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::build_results::Entity")]
    BuildResults,
}

impl Related<super::build_results::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BuildResults.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
